### PR TITLE
Add Dia da Consciência Negra as holiday in Brazil

### PR DESCRIPTION
**Pull request by adeildo-jr**
A new law published in last 21 December, determine November 20 as "Dia da Consciência Negra" national holiday in Brazil.

Sources: https://www12.senado.leg.br/noticias/materias/2023/12/22/dia-da-consciencia-negra-se-torna-feriado-nacional

https://normas.leg.br/?urn=urn:lex:br:federal:lei:2023-12-21;14759

### CODE REVIEW

**Comment by devajmeireles** [comment]
You need to update the snapshot of the test

**Comment by adeildo-jr** [comment]
@devajmeireles my bad. I'll fix and update you.

**Comment by adeildo-jr** [comment]
@devajmeireles snapshot updated

**Comment by Nielsvanpach** [comment]
Do I understand correctly this holiday is only applicable since 2023? Could you make sure this is only returned as holiday in the years this actually was official?

**Comment by adeildo-jr** [comment]
@Nielsvanpach actually, this new holiday is valid starting this in 2024. Before 2024 it was a holiday for some states only, like Rio de Janeiro and São Paulo.

I think this PR has no more sense, since #101 has been merged with the same holiday. So I'll close this PR.

**Pull request closed without merging**
