### PR TITLE
Add Ugandan Public Holidays.

### PR DESCRIPTION
**Pull request by bahiirwa**
- [x] Add all Ugandan Public Holidays.

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Could you rebase from main, so the tests can run?

**Comment by bahiirwa** [comment]
Thanks for the ping @Nielsvanpach. I have done a rebase.

**Comment by PhilN8** [comment]
Hello @bahiirwa, my name is Phil. I am also doing a PR for Kenya holidays.

How does one rebase to the `spatie:main` branch? I am having difficulties doing so

**Comment by bahiirwa** [comment]
I apologize. Can seem to get the tests running.
Let me re-open the PR afresh.

**Pull request closed without merging**
