### PR TITLE
Support for Slovenian language second PR after rebase problem

### PR DESCRIPTION
**Pull request by juref**
# Contributing a new country ?

* [yes] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/spatie/holidays/pulls) for the same country?

1. Create a new class in the Countries directory. It should extend the Country class.
2. Add a test for the new country in the tests directory.
3. Run the tests so a snapshot gets created.
4. Verify the result in the newly created snapshot is correct.

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
PR looks good! I'll wait for some approvals on the generated results before merging.

**Comment by Nielsvanpach** [comment]
If applicable, I've added support for multi language: https://github.com/spatie/holidays/pull/177

**Comment by juref** [comment]
Hey, that's great, thanks! I wanted to do PR with this feature, but unfortunately I was admitted to the hospital after an emergency. All well now!

**Comment by Nielsvanpach** [comment]
Thanks

**Pull request merged**
