### PR TITLE
Add 🇽🇰Kosovo🇽🇰 Holidays

### PR DESCRIPTION
**Pull request by AvdylKrasniqi**
TODO: Implement Islamic Holidays

### CODE REVIEW

**Comment by AvdylKrasniqi** [comment]
@Nielsvanpach @thecaliskan @alphaolomi @amralsaleeh @ddouble-d @shoxrux1996 @captainjaypee01 @kakajansh
 I saw you were involved from other PR  about the Islamic Holidays, so I am tagging you here! Perhaps we should all come with a common method in the Country class, so every country can call the method.

**Comment by ddouble-d** [comment]
> @Nielsvanpach @thecaliskan @alphaolomi @amralsaleeh @ddouble-d @shoxrux1996 @captainjaypee01 @kakajansh I saw you were involved from other PR about the Islamic Holidays, so I am tagging you here! Perhaps we should all come with a common method in the Country class, so every country can call the method.

there is one in this PR #51 that implements the islamic calendar

**Comment by AvdylKrasniqi** [comment]
> > @Nielsvanpach @thecaliskan @alphaolomi @amralsaleeh @ddouble-d @shoxrux1996 @captainjaypee01 @kakajansh I saw you were involved from other PR about the Islamic Holidays, so I am tagging you here! Perhaps we should all come with a common method in the Country class, so every country can call the method.
> 
> there is one in this PR #51 that implements the islamic calendar

I think we should implement a common method for all countries that do have Islamic holidays. On the PR #51 the solution is specifically for Malaysia

**Comment by thecaliskan** [comment]
Every year the celebration of ramadan and sacrifice holiday's dates are different in Turkey and even inside of the other Islamic countries that's why it's impossible to calculate because the countries are releasing the holiday dates six month ahead not years before.

**Comment by amralsaleeh** [comment]
> Every year the celebration of ramadan and sacrifice holiday's dates are different in Turkey and even inside of the other Islamic countries that's why it's impossible to calculate because the countries are releasing the holiday dates six month ahead not years before.

I'm with you 💯

**Comment by amralsaleeh** [comment]
So, Is there anything new?

**Comment by Nielsvanpach** [comment]
In case you want to add multi language support: https://github.com/spatie/holidays/tree/main/lang

**Pull request merged**
