### PR TITLE
Add `Egypt` Holidays

### PR DESCRIPTION
**Pull request by michaelnabil230**
There are variable holidays, but they depend on the sighting of the moon.

Reference: https://www.timeanddate.com/holidays/egypt/2024

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Could you rebase your branch on our main branch? That way I can run the tests

**Comment by michaelnabil230** [comment]
Alright, I think it's done :)

**Review by Nielsvanpach — COMMENTED** [review]
Thanks!

**Comment by michaelnabil230** [comment]
I can't be sure if it's true or not because I'm a Christian :(

**Comment by Nielsvanpach** [comment]
Thanks!

**Pull request merged**
