### PR TITLE
feat: add calendar for Nepal

### PR DESCRIPTION
**Pull request by maskeynihal**
# Contributing a new country ?

* [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/spatie/holidays/pulls) for the same country?

Add for Nepal.

### CODE REVIEW

**Comment by maskeynihal** [comment]
Need help with data collection for holiday.

**Comment by Nielsvanpach** [comment]
Thanks! Could you solve the phpstan issues?

**Comment by maskeynihal** [comment]
> Thanks! Could you solve the phpstan issues?

Just did. Can you please check it? Thanks 🙏

**Comment by Nielsvanpach** [comment]
Thanks!

**Comment by maskeynihal** [comment]
@Nielsvanpach Could you please add the "hacktoberfest-accepted" label to my PR? Thank you!

**Pull request merged**
